"""
INPUT:	
xTr : dxn input vectors
yTr : nx1 input labels
alphas : nx1 vector of alphas generated from quadratic program solution of svm
bias : bias of classifier generated by recoverBias
ktype : type of kernel
kpar : parameter of kernel
compute

Output:
svmclassify : a classifier (svmclassify(xTe) defined in this function 
that returns the binary predictions on xTe)

Creates an svm classifierthat can make predictions on new test data
"""
import numpy as np
from computeK import computeK

def createsvmclassifier(xTr, yTr, alphas, bias, ktype, kpar):

    def svmclassify(xTe):
        K = computeK(ktype, xTr, xTe, kpar)
        f = np.dot(alphas.T*yTr.T, K)+bias
        prediction = np.sign(f.T)
        return prediction

    return svmclassify